In [3]:
%pylab inline
from qutip import *

Populating the interactive namespace from numpy and matplotlib


In [24]:
e = Qobj([[2,1],[1,2]])
e

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 2.  1.]
 [ 1.  2.]]

In [25]:
e.eigenstates()

(array([ 1.,  3.]),
 array([ Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[-0.70710678]
 [ 0.70710678]],
       Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.70710678]
 [ 0.70710678]]], dtype=object))

In [26]:
pz = Qobj([[1],[0]])
mz = Qobj([[0],[1]])
px = Qobj([[1/sqrt(2)],[1/sqrt(2)]])
mx = Qobj([[1/sqrt(2)],[-1/sqrt(2)]])
py = Qobj([[1/sqrt(2)],[1j/sqrt(2)]])
my = Qobj([[1/sqrt(2)],[-1j/sqrt(2)]])
Sx = 1/2.0*sigmax()
Sy = 1/2.0*sigmay()
Sz = 1/2.0*sigmaz()

In [48]:
psi = 1/sqrt(5)*py + 1/sqrt(5)*px + 1/sqrt(3)*pz
psi.norm()

1.289817846315345

In [39]:
psi.dag()*e*psi

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 3.41421356]]

In [32]:
psi.dag()*e*e*psi

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 7.66666667 -2.22044605e-16j]]

In [33]:
7.66 - 2.6**2

0.8999999999999995