In [1]:
import matplotlib.pyplot as plt
from numpy import *
from qutip import *

In [2]:
H = Qobj([[1],[0]])
V = Qobj([[0],[1]])
P45 = Qobj([[1/sqrt(2)],[1/sqrt(2)]])
M45 = Qobj([[1/sqrt(2)],[-1/sqrt(2)]])
R = Qobj([[1/sqrt(2)],[-1j/sqrt(2)]])
L = Qobj([[1/sqrt(2)],[1j/sqrt(2)]])

In [3]:
R

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678+0.j        ]
 [0.        -0.70710678j]]

In [4]:
def HWP(theta):
    return Qobj([[cos(2*theta),sin(2*theta)],[sin(2*theta),-cos(2*theta)]]).tidyup()

In [5]:
HWP(0)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [6]:
def LP(theta):
    return Qobj([[cos(theta)**2,cos(theta)*sin(theta)],[sin(theta)*cos(theta),sin(theta)**2]]).tidyup()

In [7]:
def QWP(theta):
    return Qobj([[cos(theta)**2 + 1j*sin(theta)**2,
                 (1-1j)*sin(theta)*cos(theta)],
                [(1-1j)*sin(theta)*cos(theta),
                 sin(theta)**2 + 1j*cos(theta)**2]]).tidyup()

In [8]:
out = LP(pi/4)*V
out

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.5]
 [0.5]]

In [9]:
1/sqrt(2)*P45

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.5]
 [0.5]]

In [10]:
1/2.0*H + 1/2.0*V

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.5]
 [0.5]]

In [11]:
out.norm()  # equivalent to sqrt(0.5**2 + 0.5**2)

0.7071067811865475