In [1]:
from qutip import *

In [2]:
# Create a row vector:
rv = Qobj([[1,2]])
rv

Quantum object: dims = [[1], [2]], shape = (1, 2), type = bra
Qobj data =
[[1. 2.]]

In [3]:
# Find the corresponding column vector
rv.dag()

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [2.]]

In [4]:
# Create a column vector:
cv = Qobj([[1],[4]])
cv

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [4.]]

In [5]:
# Convert to a row vector:
cv.dag()

Quantum object: dims = [[1], [2]], shape = (1, 2), type = bra
Qobj data =
[[1. 4.]]

In [6]:
rv*cv  # inner product (dot product)

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[9.]]

In [7]:
rv*rv.dag()  # dot product with itself, need row vector first

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[5.]]

In [8]:
rv.norm() # find the length of the vector

2.23606797749979

In [9]:
# verify that the norm of the vector is the square root of the dot product with itself:
from numpy import sqrt, cos, sin, pi
sqrt(5)

2.23606797749979

In [10]:
qm = Qobj([[1,2],[2,1]])
qm

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 2.]
 [2. 1.]]

In [11]:
qm.eigenenergies()  # in quantum (as we will learn) eigenvalues often correspond to energy levels

array([-1.,  3.])

In [12]:
evals, evecs = qm.eigenstates()

In [13]:
evecs

array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[-0.70710678]
 [ 0.70710678]],
       Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]], dtype=object)

In [14]:
# Select the first eigenvector using an index inside square brackets:
# Index counting starts at zero so [0] picks the first one:
evecs[0]

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[-0.70710678]
 [ 0.70710678]]

In [15]:
# States:
horiz = Qobj([[1],[0]])
vert = Qobj([[0],[1]])
p45 = 1/sqrt(2)*Qobj([[1],[1]])
m45 = 1/sqrt(2)*Qobj([[1],[-1]])
lcp = 1/sqrt(2)*Qobj([[1],[1j]])
rcp = 1/sqrt(2)*Qobj([[1],[-1j]])

# Operators:
HP = Qobj([[1,0],[0,0]])
VP = Qobj([[0,0],[0,1]])
qwp_p45 = 1/sqrt(2)*Qobj([[1,-1j],[-1j,1]])
qwp_m45 = 1/sqrt(2)*Qobj([[1,1j],[1j,1]])

In [16]:
# To display one of these, simply put it at the end of a cell:
VP

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 1.]]

In [17]:
# An example calculation, the state of light after +45 polarization goes through a horizontal polarizer:
HP*p45

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]]

In [18]:
def HWP(theta):
    return Qobj([[cos(2*theta),sin(2*theta)],[sin(2*theta),-cos(2*theta)]]).tidyup()

def LP(theta):
    return Qobj([[cos(theta)**2,cos(theta)*sin(theta)],[sin(theta)*cos(theta),sin(theta)**2]]).tidyup()

def QWP(theta):
    return Qobj([[cos(theta)**2 + 1j*sin(theta)**2,
                 (1-1j)*sin(theta)*cos(theta)],
                [(1-1j)*sin(theta)*cos(theta),
                 sin(theta)**2 + 1j*cos(theta)**2]]).tidyup()

In [19]:
# Solution
total = QWP(pi/4)*QWP(pi/2)*HWP(pi/8)

total*horiz

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.        +0.j        ]
 [0.70710678+0.70710678j]]

In [20]:
# Solution
result = HWP(pi/1.5)*rcp
result

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[-0.35355339+0.61237244j]
 [-0.61237244-0.35355339j]]

In [21]:
# Solution
result.dag()*rcp

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

In [22]:
# Solution
from numpy import linspace
for angle in linspace(0,pi,20): # define a linearly-spaced list of 20 values between 0 and pi
    print( (HWP(angle)*rcp).dag()*rcp )

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
Quantum object: dims = [[1],

In [23]:
# Solution
total = QWP(-pi/4)*HP*QWP(pi/4)

total*lcp # Allows LCP through

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.        +0.70710678j]
 [-0.70710678+0.j        ]]

In [24]:
total*rcp  # does not allow RCP

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [0.]]

In [25]:
# Solution
total = QWP(-pi/4)*VP*QWP(pi/4)

total*lcp # Does not allow LCP through

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [0.]]

In [26]:
total*rcp # Allows RCP completely

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.        +0.70710678j]
 [0.70710678+0.j        ]]